name: moon_ruler_picker
description: "Deliver a superior user experience through the smoothly customized Ruler Picker, featuring natural swipe acceleration and resistance!"
version: 1.0.3
homepage: "https://github.com/icecrao2/moon_ruler_picker"
repository: "https://github.com/icecrao2/moon_ruler_picker"

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

platforms:
  android:
  ios:

flutter:
